"""empty message

Revision ID: 3b4662a30e8e
Revises: 
Create Date: 2025-01-01 17:54:14.437144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4662a30e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alis_hareketleri',
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Float(), nullable=False),
    sa.Column('birimfiyati', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eticaret',
    sa.Column('adi', sa.String(), nullable=False),
    sa.Column('adres', sa.String(), nullable=False),
    sa.Column('telefon', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategori',
    sa.Column('kategoriadi', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satis_hareketleri',
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Float(), nullable=False),
    sa.Column('birimfiyati', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siparis',
    sa.Column('tarih', sa.String(), nullable=False),
    sa.Column('firma', sa.String(), nullable=False),
    sa.Column('musteri', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urun',
    sa.Column('urun_kodu', sa.String(), nullable=False),
    sa.Column('urun_adi', sa.String(), nullable=False),
    sa.Column('fiyat', sa.Float(), nullable=False),
    sa.Column('acıklama', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urun_kodu')
    )
    op.create_table('urunozellikleri',
    sa.Column('urun', sa.String(), nullable=False),
    sa.Column('değer', sa.String(), nullable=False),
    sa.Column('özellik', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urun')
    )
    op.create_table('urunyorumu',
    sa.Column('siparis', sa.String(), nullable=False),
    sa.Column('urun', sa.String(), nullable=False),
    sa.Column('yorum', sa.Float(), nullable=False),
    sa.Column('puan', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ekleme_tarihi', sa.DateTime(), nullable=False),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siparis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urunyorumu')
    op.drop_table('urunozellikleri')
    op.drop_table('urun')
    op.drop_table('siparis')
    op.drop_table('satis_hareketleri')
    op.drop_table('kategori')
    op.drop_table('eticaret')
    op.drop_table('alis_hareketleri')
    # ### end Alembic commands ###
